import re

def convert_time(srt_time):
    # 将SRT时间格式（00:00:00,000）转换为ASS时间格式（0:00:00.00）
    hours, minutes, seconds = srt_time.split(':')
    seconds, milliseconds = seconds.split(',')
    return f"{int(hours)}:{minutes}:{seconds}.{int(milliseconds)//10}"

def srt_to_ass(srt_file_path, ass_file_path):
    with open(srt_file_path, 'r', encoding='utf-8') as srt_file:
        srt_content = srt_file.read()

    # 初始化ASS文件的头部信息
    ass_content = """[Script Info]
Title: Generated by Script
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: None

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H80000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""

    # 解析SRT文件并转换为ASS格式
    entries = re.split(r'\n\n+', srt_content)  # 分割字幕条目
    for entry in entries:
        lines = entry.split('\n')
        if len(lines) < 3: continue  # 如果条目不完整，则跳过

        # 获取时间和文本
        times = re.match(r'(\d{2}:\d{2}:\d{2},\d{3}) --> (\d{2}:\d{2}:\d{2},\d{3})', lines[1])
        if not times: continue  # 如果没有匹配到时间，则跳过

        start_time = convert_time(times.group(1))
        end_time = convert_time(times.group(2))
        text = '\\N'.join(lines[2:])  # 将文本行合并，用'\N'代替换行符

        ass_content += f"Dialogue: 0,{start_time},{end_time},Default,,0,0,0,,{text}\n"

    # 写入ASS文件
    with open(ass_file_path, 'w', encoding='utf-8') as ass_file:
        ass_file.write(ass_content)


